[project]
name = "vizdyn"
version = "0.2.0"
description = "App to visualize dynamics in various ways."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "pyqt5>=5.15.11",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.0",
]
