[project]
name = "visualizedynamics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "pyqt5>=5.15.11",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.0",
]
